### ISSUE TITLE
Shops de palier

### ISSUE THREAD

**Issue by HevelMc** [HevelMc/Electryon#1]
### **Système de shop**

**Nécessite:** 
- [x] Correction de bug du plugin Skript (ajout des named item dans les menus) #37 
- [ ] Correction de bug du plugin Skript (ajout des lore dans les menus) #38 

**Pour**:
- [x] Finir le code
- [ ] Remplir les shops #42
